title: Mon Site Minimal Mistakes
description: Un site super stylé avec GitHub Actions
baseurl: "" # À modifier si ton site est dans un sous-dossier
url: "https://jibiyatuche.github.io"

theme: minimal-mistakes-jekyll

plugins:
  - jekyll-include-cache
