title: jibiyatuche
description: Si tu aimes le hacking :)
baseurl: "/Website" 
url: "https://jibiyatuche.github.io"

theme: minimal-mistakes-jekyll

plugins:
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true
